### ISSUE TITLE
Commit metadata?

### ISSUE THREAD

**Issue by pravic** [LucioFranco/ghp-rs#3]
As I see, currently there is [no commit author](https://github.com/LucioFranco/ghp-rs/commits/gh-pages) specified  for gh-pages. Is it expected?

**Comment by LucioFranco** [comment]
@pravic it seems to work for me on a test that I did that was pushed from my computer. https://github.com/LucioFranco/website/commits/gh-pages

Maybe it is something to do with travis?

**Comment by pravic** [comment]
Well, I just wanted to be sure.

**Comment by LucioFranco** [comment]
I'm going to close this as it seems like the issues isn't with this project. Feel free to reopen if you feel the need.
