### ISSUE TITLE
Appveyor build issues

### ISSUE THREAD

**Issue by LucioFranco** [LucioFranco/ghp-rs#6]
I do not have a windows so debugging is not very easy.

**Comment by LucioFranco** [comment]
@pravic if you are on a windows computer could you try the test script you wrote. It seems on appveyor it doesn't work. The appveyor link is in the README.

**Comment by pravic** [comment]
Check PR #7.

> The appveyor link is in the README.

This link is broken: it points to `https://github.com/LucioFranco/ghp-rs/blob/master` instead of `https://ci.appveyor.com/project/LucioFranco/ghp-rs/`
